<?php namespace Sas\Erp\Components;

use Cms\Classes\ComponentBase;
use Cms\Classes\Page;
use Sas\Erp\Models\FeedbackChannel;
use Lang;
use October\Rain\Exception\AjaxException;

class Feedback extends ComponentBase
{

    /**
     * @var Channel
     */
    public $channel;

    public function componentDetails()
    {
        return [
            'name'        => Lang::get('sas.erp::lang.feedback.component.feedback.name'),
            'description' => Lang::get('sas.erp::lang.feedback.component.feedback.description')
        ];
    }

    public function defineProperties()
    {
        return [
            'channelCode' => [
                'title' => Lang::get('sas.erp::lang.feedback.channel.one'),
                'description' => Lang::get('sas.erp::lang.feedback.component.feedback.channelCode.description'),
                'type' => 'dropdown',
                'required' => true
            ],
            'successMessage' => [
                'title' => Lang::get('sas.erp::lang.feedback.component.feedback.successMessage.title'),
                'description' => Lang::get('sas.erp::lang.feedback.component.feedback.successMessage.description')
            ],
            'redirectTo' => [
                'title' => Lang::get('sas.erp::lang.feedback.component.feedback.redirectTo.title'),
                'description' => Lang::get('sas.erp::lang.feedback.component.feedback.redirectTo.description'),
                'type' => 'dropdown',
                'default' => 0
            ]
        ];
    }

    /**
     * @throws \October\Rain\Database\ModelException
     */
    public function onSend()
    {
        try {
            $data = post('feedback');
            $channel = FeedbackChannel::getByCode($this->property('channelCode'));
            if ($channel) {
                $channel->send($data);
            }
            else {
                $this->sendAdminEmail('Error on Feedback plugin', 'This message was generated by OctoberCMS\'s plugin Feedback. This message is send when you forget to configure your component. Please, check all your pages to find any Feedback component misconfigured.');
            }

            $message = $this->property('successMessage', Lang::get('sas.erp::lang.feedback.component.onSend.success'));
            \Flash::success($message);
            if ($this->property('redirectTo', false)) {
                return redirect(url($this->property('redirectTo')));
            }
            else {
                return $message;
            }
        }
        catch (\Exception $e) {
            \Flash::error($e->getMessage());
            throw new AjaxException($e->getMessage());
        }
    }

    public function onRun()
    {
        $this->channel = FeedbackChannel::getByCode($this->property('channelCode'));
    }

    public function getRedirectToOptions()
    {
        return array_merge([0 => '- none -'], Page::sortBy('baseFileName')->lists('fileName', 'url'));
    }

    public function getChannelCodeOptions()
    {
        return FeedbackChannel::all()->lists('name', 'code');
    }

    private function sendAdminEmail($subject, $message)
    {
        $channel = new FeedbackChannel([
            'method' => 'email',
            'method_data' => [
                'email_destination' => null,
                'subject' => $subject,
                'template' => $message
            ],
            'prevent_save_database' => true
        ]);
        $channel->send([
            'email' => 'foo@bar.com',
            'message' => 'loremipsum'
        ]);
    }

}
